In [1]:
using JLD2
using DelimitedFiles

In [2]:
# ko = load_object("./KOSimulatedDataSets.jld2")
data_in = load_object("./randomNetworkTimeSeriesSimData.jld2")

10×801×2000×117 Array{Float32, 4}:
[:, :, 1, 1] =
 1.0   0.919454    0.900428    0.814584    …  2.00259     1.86182     0.0
 0.01  0.0087436   0.0116805   0.0397242      0.00688109  0.00737121  0.0
 0.01  0.206237    0.40003     0.490763       0.110588    0.0613785   0.0
 0.01  0.00792303  0.00222643  5.695f-6       1.82633     1.76358     0.0
 0.01  0.0149566   0.00338211  0.00338211     0.0510626   0.0462409   0.0
 0.01  0.0156799   0.0132413   0.0415806   …  2.02806     2.18347     0.0
 0.01  0.197273    0.363233    0.414504       0.00233846  0.00282893  0.0
 0.01  0.00717269  0.00387277  0.0102284      0.0121545   0.014101    0.0
 0.01  0.107738    0.199548    0.245369       0.0167237   0.0167237   0.0
 0.01  0.0217326   0.0217326   0.0362864      2.18155     2.22867     0.0

[:, :, 2, 1] =
 1.0   0.891219    0.943418    0.876592    …  1.85273      1.879        0.0
 0.01  0.00593192  0.00284273  0.0104616      0.000152133  0.00131721   0.0
 0.01  0.197168    0.345189    0.564636   

In [3]:
maybe_bifur = data_in[3:end,2:end,:,1]

8×800×2000 Array{Float32, 3}:
[:, :, 1] =
 0.206237    0.40003     0.490763    …  0.110588    0.0613785   0.0
 0.00792303  0.00222643  5.695f-6       1.82633     1.76358     0.0
 0.0149566   0.00338211  0.00338211     0.0510626   0.0462409   0.0
 0.0156799   0.0132413   0.0415806      2.02806     2.18347     0.0
 0.197273    0.363233    0.414504       0.00233846  0.00282893  0.0
 0.00717269  0.00387277  0.0102284   …  0.0121545   0.014101    0.0
 0.107738    0.199548    0.245369       0.0167237   0.0167237   0.0
 0.0217326   0.0217326   0.0362864      2.18155     2.22867     0.0

[:, :, 2] =
 0.197168   0.345189    0.564636    …  7.68529f-7  7.63356f-5   0.0
 0.0220946  0.0339415   0.0321026      2.27612     2.20132      0.0
 0.0173003  0.0134186   0.0219557      0.0268688   0.000598806  0.0
 0.0069105  0.00336661  0.00336661     2.01644     1.9022       0.0
 0.198488   0.356577    0.494211       0.00759366  0.0113414    0.0
 0.0207718  0.0231632   0.0257048   …  0.0159504   0.0171728 

In [4]:
flat = reshape(maybe_bifur,(8,1600000))

8×1600000 Matrix{Float32}:
 0.206237    0.40003     0.490763    …  0.100405    0.0834544   0.0
 0.00792303  0.00222643  5.695f-6       2.62658     2.33765     0.0
 0.0149566   0.00338211  0.00338211     0.0190453   0.0290443   0.0
 0.0156799   0.0132413   0.0415806      2.08662     2.09539     0.0
 0.197273    0.363233    0.414504       0.00105238  0.00559581  0.0
 0.00717269  0.00387277  0.0102284   …  0.00441589  0.00821595  0.0
 0.107738    0.199548    0.245369       0.0187197   0.0113617   0.0
 0.0217326   0.0217326   0.0362864      1.77239     1.78359     0.0

In [5]:
maybe_bifur[:,1,1]

8-element Vector{Float32}:
 0.20623733
 0.007923031
 0.014956551
 0.015679913
 0.19727339
 0.0071726926
 0.10773795
 0.021732619

In [6]:
maybe_bifur[:,2,1]

8-element Vector{Float32}:
 0.40003017
 0.0022264319
 0.0033821084
 0.013241337
 0.363233
 0.0038727727
 0.19954784
 0.021732619

In [7]:
flat[:,1]

8-element Vector{Float32}:
 0.20623733
 0.007923031
 0.014956551
 0.015679913
 0.19727339
 0.0071726926
 0.10773795
 0.021732619

In [8]:
flat[:,2]

8-element Vector{Float32}:
 0.40003017
 0.0022264319
 0.0033821084
 0.013241337
 0.363233
 0.0038727727
 0.19954784
 0.021732619

In [9]:
writedlm("maybe_bifur.tsv",transpose(flat))